// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:on_device_ai/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ChaptersAdapter());
    registerAdapter(PerformanceAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(SubjectAdapter());
    registerAdapter(SubjectGeneratedTextAdapter());
    registerAdapter(SubtopicsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ChaptersAdapter());
    registerAdapter(PerformanceAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(SubjectAdapter());
    registerAdapter(SubjectGeneratedTextAdapter());
    registerAdapter(SubtopicsAdapter());
  }
}
